openapi: 3.0.0

components:
  requestBodies:
    # SAMPLE BODY
    PostSampleBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                type: string
                minLength: 1
                maxLength: 100
              lastname:
                type: string
                minLength: 1
                maxLength: 100
            required:
              - name
    PutSampleBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                type: string
                minLength: 1
                maxLength: 100
              lastname:
                type: string
                minLength: 1
                maxLength: 100
  schemas:
    # SAMPLE MODEL
    Sample:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          minLength: 1
          maxLength: 100
        lastname:
          type: string
          minLength: 0
          maxLength: 100
