openapi: 3.0.0

components:
  schemas:
    # SAMPLE RESPONSE
    Sample:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        lastname:
          type: string
